// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4C3zlRRMzmgB7CxtceXa99vJHQO1UXiM',
    appId: '1:297464483731:web:13be1da9adeef351072266',
    messagingSenderId: '297464483731',
    projectId: 'socialmedia-d5a76',
    authDomain: 'socialmedia-d5a76.firebaseapp.com',
    storageBucket: 'socialmedia-d5a76.appspot.com',
    measurementId: 'G-48Q8Z0MTPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDimbzIoZchdt28l6Pu3geBvFOaKiZhR_Q',
    appId: '1:297464483731:android:4902594361f561b4072266',
    messagingSenderId: '297464483731',
    projectId: 'socialmedia-d5a76',
    storageBucket: 'socialmedia-d5a76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxjPdqYpF-H37Z6OGTwWs0ZPVA0UXH2lI',
    appId: '1:297464483731:ios:ade6750708fbbcd8072266',
    messagingSenderId: '297464483731',
    projectId: 'socialmedia-d5a76',
    storageBucket: 'socialmedia-d5a76.appspot.com',
    iosBundleId: 'com.example.socialmedia',
  );
}
